Feature/article detail
dbrimeUQAM/steady-roll-angular pull request #12
Opened 2020-07-05 01:02 UTC by GhadaSou

2020-07-05 14:27 UTC, MassekMeriam submitted a review, later dismissed

2020-07-05 16:59 UTC, dbrimeUQAM requested changes

2020-07-05 16:59 UTC, dbrimeUQAM commented on src/app/header/header.component.html
> +    {{ name }} ( {{ hospitalName }} )
Le nom d'hopital est trop gross. Ça pousse trop le nom de l'utilisateur.
Font plus petite, dans un autre ligne aussi et on enleve les parentheses svp.
![image](https://user-images.githubusercontent.com/64797121/86537277-f9f58380-bebb-11ea-917b-9397f9ec97ed.png)

2020-07-05 16:59 UTC, dbrimeUQAM commented on src/app/add-article/add-article.component.html
> +<form [formGroup]="articleFrom" class="forme">
Je trouve trop large le formulaire. Est-ce qu'on peut l'ajusté? On devrait avoir un max width quelque part.

2020-07-05 16:59 UTC, dbrimeUQAM commented on src/app/add-article/add-article.component.html
> +        <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
Le format de la date est MM/DD. Changer a DD/MM svp.

2020-07-05 16:59 UTC, dbrimeUQAM commented on src/app/add-article/add-article.component.html
> +        color="primary" (click)="submit()">Ajouter</button>
pas sur si deja fonctionnelle mais si je click ajouter sans rien remplir, les validations sont montré par un instant mais l'article est crée vide et je suis redirigé au home page.

2020-07-05 16:59 UTC, dbrimeUQAM commented on src/app/add-article/add-article.component.ts
> +    this.article.hospitalName = this.hospitalName ;
On sauvegarde pas le nom de l'hopital dans l'article. Enlever svp.

2020-07-05 16:59 UTC, dbrimeUQAM commented on src/app/add-article/add-article.component.ts
> +    this.hospitalName = this.tokenStorage.getUser().hospital.name;
pas besoin ici.

2020-07-05 16:59 UTC, dbrimeUQAM commented on src/app/add-article/add-article.component.ts
> +  hospitalName: string;
pas besoin ici

2020-07-05 16:59 UTC, dbrimeUQAM commented on src/app/article-detail/article-detail.component.html
> +    <button mat-raised-button style="background-color: #097D6C; color: white;" (click)="openDialog(article.name, article.articleType)" >Ajouter au panier</button>
si tu vais pas utiliser la palette de couleur de Material je recommande un classe au lie de mettre du style partout que se repete.

2020-07-05 16:59 UTC, dbrimeUQAM commented on src/app/header/header.component.html
> +<mat-toolbar style="background-color: #097D6C; color: white;">
classe

2020-07-05 16:59 UTC, dbrimeUQAM commented on src/app/header/header.component.ts
> +import { ArticleService } from '../services/article/article.service';
pas sur de comprendre pourquoi on a besoin d'ArticleService ici.

Si je comprend bien tu veux le length the 'articles' dans l'order (si disponible) dans le tokenStorageService

2020-07-05 16:59 UTC, dbrimeUQAM commented on src/app/header/header.component.ts
> +      this.articleNum = this.articles.length ;
Ça devrait être plus tot quelque chose comme ca:
```
 this.articleNum = this.tokenStorage.getUser().order ? this.tokenStorage.getUser().order.articles.length : 0;
```

2020-07-05 16:59 UTC, dbrimeUQAM commented on src/app/home-page/home-page.component.html
> +  <button style="background-color: #097D6C; color: white;" mat-raised-button color="primary" [routerLink]="'/add-article'" >Ajouter un article</button>
classe ;-)

2020-07-05 16:59 UTC, dbrimeUQAM commented on src/app/register/register.component.html
> +        <button style="background-color: #097D6C; color: white;" class="btn btn-primary btn-block">S'inscrire</button>
classe

2020-07-05 16:59 UTC, dbrimeUQAM commented on src/app/services/bag/bag.service.ts
> +const apiUrl = environment.production ? '/api/articles/' : 'http://localhost:3000/api/articles';
Ici on devrait utiliser l'API pour orders et pas celle pour articles.

2020-07-05 17:12 UTC, GhadaSou commented on src/app/header/header.component.html
> +    {{ name }} ( {{ hospitalName }} )
je vais regler ca

2020-07-05 17:13 UTC, GhadaSou commented on src/app/add-article/add-article.component.html
> +<form [formGroup]="articleFrom" class="forme">
add-article c le travail de @sanajaziri

2020-07-05 17:14 UTC, GhadaSou commented on src/app/add-article/add-article.component.html
> +        <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
je vais le fixer

2020-07-05 17:15 UTC, GhadaSou commented on src/app/header/header.component.ts
> +import { ArticleService } from '../services/article/article.service';
jai utilisé articleService juste pour avoir une idée de l'affichage, en attendant que @MassekMeriam  finisse son job pour order service

2020-07-05 17:17 UTC, GhadaSou commented on src/app/header/header.component.ts
> +      this.articleNum = this.articles.length ;
meme chose j'attends le order service .. mais pour le moment j'ai fait le PR juste pour que Master soit un peu à jour

2020-07-05 17:17 UTC, GhadaSou commented on src/app/home-page/home-page.component.html
> +  <button style="background-color: #097D6C; color: white;" mat-raised-button color="primary" [routerLink]="'/add-article'" >Ajouter un article</button>
j'ai pas compris ?

2020-07-05 17:18 UTC, GhadaSou commented on src/app/register/register.component.html
> +        <button style="background-color: #097D6C; color: white;" class="btn btn-primary btn-block">S'inscrire</button>
?

2020-07-05 17:27 UTC, dbrimeUQAM commented on src/app/header/header.component.ts
> +import { ArticleService } from '../services/article/article.service';
@GhadaSou je comprends, par contre ici tu a juste besoin de la valeur en token service.

On devrait pas faire un appel a order service ici.
Apres quand l'utilisateur manipule l'order tu peut garder a jour la valeur dans token storage pour l'afficher.

2020-07-05 17:29 UTC, dbrimeUQAM commented on src/app/home-page/home-page.component.html
> +  <button style="background-color: #097D6C; color: white;" mat-raised-button color="primary" [routerLink]="'/add-article'" >Ajouter un article</button>
t'as mis ```style="background-color: #097D6C; color: white;```
dans plusieurs places. 
On pourrait le mettre dans le CSS du projet si jamais on a besoin de modifier ça sera juste dans un place.

2020-07-05 17:29 UTC, dbrimeUQAM commented on src/app/register/register.component.html
> +        <button style="background-color: #097D6C; color: white;" class="btn btn-primary btn-block">S'inscrire</button>
repondu plus haut

2020-07-05 17:34 UTC, GhadaSou commented on src/app/header/header.component.html
> +    {{ name }} ( {{ hospitalName }} )
![image](https://user-images.githubusercontent.com/46688476/86538479-41800d80-bec4-11ea-80e2-93880d69baf2.png)

2020-07-05 17:35 UTC, GhadaSou commented on src/app/header/header.component.html
> +    {{ name }} ( {{ hospitalName }} )
![image](https://user-images.githubusercontent.com/46688476/86538491-4e046600-bec4-11ea-8799-26887f8f10fb.png)

2020-07-05 20:55 UTC, sanajaziri submitted a review, later dismissed

2020-07-05 22:25 UTC, MassekMeriam commented on src/app/header/header.component.ts
> +import { ArticleService } from '../services/article/article.service';
je vais faire ca

2020-07-05 22:26 UTC, MassekMeriam commented on src/app/services/bag/bag.service.ts
> +const apiUrl = environment.production ? '/api/articles/' : 'http://localhost:3000/api/articles';
ça aussi je vais le modifier

2020-07-06 03:44 UTC, sanajaziri submitted a review, later dismissed

2020-07-07 01:09 UTC, merged