Order service
dbrimeUQAM/steady-roll-angular pull request #13
Opened 2020-07-05 20:46 UTC by MassekMeriam

2020-07-05 20:54 UTC, sanajaziri approved these changes

2020-07-05 22:22 UTC, dbrimeUQAM requested changes

2020-07-05 22:22 UTC, dbrimeUQAM commented on routes/orders.js
> +                return res.status(200).json(articles);
pas sur de comprendre ici. Ça sert a quoi cette route?
Et comme nous sommes dans le service Order je m'attend a retourner une order et pas des articles.

2020-07-05 22:22 UTC, dbrimeUQAM commented on src/app/bag-page/bag-page.component.ts
> +    this.orderService.getAll(this.tokenStorage.getUser().id)
cette methode devrait s'appeler .getCurrentOrder au lieu de .getAll probablement

2020-07-05 22:22 UTC, dbrimeUQAM commented on routes/orders.js
> +                for (i = 0; i < articles.length; i++) {
t'as pas de garantie que les articles revient dans le meme ordre que ils sont dans l'order.
Utiliser un ```.map``` our ```.forEach``` ici au lieu du boucle for.

2020-07-05 22:22 UTC, dbrimeUQAM commented on src/app/header/header.component.ts
> +  constructor(private orderService: OrderService, private router: Router, private tokenStorage: TokenStorageService) { }
il faut faire un appel a orderService ici. pas necessaire, deja fait au login

2020-07-05 22:22 UTC, dbrimeUQAM commented on src/app/header/header.component.ts
> +    this.orderService.getAll(this.tokenStorage.getUser().id).subscribe(data => {
a ce moment le seule que on veut savoir est la qty dans le bag donce on a deja ca dans le tokenStorage.
On se occupe de l'order plus tard si l'utilisateur rentre dans le panier par exemple.

2020-07-05 22:22 UTC, dbrimeUQAM commented on src/app/services/order/order.service.ts
> +  getAll(userId: string): Observable<Article[]> {
changer le nom de la methode a quelque chose comme getCurrentOrder et retourne l'order au complet, pas juste le tableau d'articles.

2020-07-05 22:52 UTC, MassekMeriam commented on routes/orders.js
> +                return res.status(200).json(articles);
on a besoin des articles de ce order pour afficher le panier

2020-07-05 22:58 UTC, MassekMeriam commented on src/app/bag-page/bag-page.component.ts
> +    this.orderService.getAll(this.tokenStorage.getUser().id)
done

2020-07-05 22:59 UTC, MassekMeriam commented on routes/orders.js
> +                for (i = 0; i < articles.length; i++) {
2 boucles imbriqués alors pour vérifier pour chaque article

2020-07-05 23:00 UTC, MassekMeriam commented on src/app/header/header.component.ts
> +  constructor(private orderService: OrderService, private router: Router, private tokenStorage: TokenStorageService) { }
done

2020-07-05 23:01 UTC, MassekMeriam commented on src/app/header/header.component.ts
> +    this.orderService.getAll(this.tokenStorage.getUser().id).subscribe(data => {
done mais là il faut touours penser à mettre à jour la bd et à mettre à jour tokenStorage

2020-07-05 23:23 UTC, dbrimeUQAM commented on routes/orders.js
> +                return res.status(200).json(articles);
@MassekMeriam 
d'accord retourne l'ordre au complet juste en modifiant les articles. Pas juste les articles.

2020-07-05 23:25 UTC, dbrimeUQAM commented on src/app/header/header.component.ts
> +    this.orderService.getAll(this.tokenStorage.getUser().id).subscribe(data => {
@MassekMeriam oui, exact. Si le panier est touché on met a jour token storage.

2020-07-05 23:38 UTC, dbrimeUQAM requested changes

2020-07-05 23:38 UTC, dbrimeUQAM commented on routes/orders.js
> +                for (i = 0; i < articles.length; i++) {
@MassekMeriam non, tu peux faire un  ```.map``` avec un ```.find``` a l'interieur.
Par exemple, il faut le tester.
```
clientOrder.articles = clientOrder.articles.map(article => {
   let articleDoc = articles.find(item => item._id === article._id);
  
  if (articleDoc) {
     return { ...articleDoc, ...article };
  }

  return article;

});
```

2020-07-05 23:38 UTC, dbrimeUQAM commented on routes/orders.js
> +                return res.status(200).json(articles);
return res.status(200).json(clientOrder);

2020-07-05 23:38 UTC, dbrimeUQAM commented on src/app/header/header.component.ts
> +    this.articleNum = this.tokenStorage.getUser().order.articles.length ;
@MassekMeriam  oublier pas de verifier que order n'est pas null sinon ça va faire une exception ici.

2020-07-05 23:38 UTC, dbrimeUQAM commented on src/app/services/order/order.service.ts
> +import { Article } from './article';
remplacer par
import { Order } from './order';

2020-07-05 23:38 UTC, dbrimeUQAM commented on src/app/services/order/order.service.ts
> +    return this.httpClient.get<Article[]>(url)
remplacer par
return this.httpClient.get<Order>(url)

2020-07-05 23:38 UTC, dbrimeUQAM commented on src/app/bag-page/bag-page.component.ts
>        this.articles = res;
remplacer par
this.order = res;

2020-07-05 23:38 UTC, dbrimeUQAM commented on src/app/bag-page/bag-page.component.ts
>        this.dataSource = new MatTableDataSource(this.articles);
remplacer par 
this.dataSource = new MatTableDataSource(this.order.articles);

2020-07-05 23:38 UTC, dbrimeUQAM commented on src/app/bag-page/bag-page.component.ts
> +      console.log("orderService . get all");
effacer les console.log si plus necessaire

2020-07-06 00:00 UTC, GhadaSou approved these changes

2020-07-06 00:42 UTC, merged