Feature/sr 56
dbrimeUQAM/steady-roll-angular pull request #20
Opened 2020-07-11 23:33 UTC by GhadaSou

2020-07-11 23:58 UTC, dbrimeUQAM requested changes

2020-07-11 23:58 UTC, dbrimeUQAM commented on src/app/header/header.component.ts
> +    this.orderService.getCurrentOrder(this.tokenStorage.getUser().id)
pourquoi tu recupere l'order dans le header?

2020-07-12 00:06 UTC, sanajaziri submitted a review, later dismissed

2020-07-12 00:08 UTC, GhadaSou commented on src/app/header/header.component.ts
> +    this.orderService.getCurrentOrder(this.tokenStorage.getUser().id)
![image](https://user-images.githubusercontent.com/46688476/87236072-3f311e00-c3b2-11ea-95e1-0b9b25fa27fb.png)

2020-07-12 00:08 UTC, GhadaSou commented on src/app/header/header.component.ts
> +    this.orderService.getCurrentOrder(this.tokenStorage.getUser().id)
pour afficher le nombre d'articles dans le panier

2020-07-12 00:09 UTC, GhadaSou commented on src/app/header/header.component.ts
> +    this.orderService.getCurrentOrder(this.tokenStorage.getUser().id)
![image](https://user-images.githubusercontent.com/46688476/87236082-6daef900-c3b2-11ea-83e0-bdf526029b70.png)

2020-07-12 00:09 UTC, GhadaSou commented on src/app/header/header.component.ts
> +    this.orderService.getCurrentOrder(this.tokenStorage.getUser().id)
ca a partir de master j'ai deux articles mais c marqué 0

2020-07-12 00:29 UTC, MassekMeriam submitted a review, later dismissed

2020-07-12 00:44 UTC, dbrimeUQAM requested changes

2020-07-12 00:44 UTC, dbrimeUQAM commented on src/app/header/header.component.ts
> +    this.orderService.getCurrentOrder(this.tokenStorage.getUser().id)
C'est deja calcule dans le token storage. Pas besoin de faire ca a chaque fois que ouvre le header.

C'est la ligne suivante que t'as remplacée

this.articleNum = user.order ? user.order.articles.length : 0 ;

2020-07-12 00:44 UTC, dbrimeUQAM commented on src/app/header/header.component.ts
> +    this.articleNum = this.tokenStorage.getUser().hospital.order ? this.tokenStorage.getUser().hospital.articles.length : 0 ;
c'est ligne n'existe pas
hospital.order???

2020-07-12 01:59 UTC, GhadaSou commented on src/app/header/header.component.ts
> +    this.articleNum = this.tokenStorage.getUser().hospital.order ? this.tokenStorage.getUser().hospital.articles.length : 0 ;
hhhh tu as raison et c pour ca il n'affiche rien

2020-07-13 16:09 UTC, dbrimeUQAM approved these changes

2020-07-13 16:09 UTC, merged