Feature/login component
dbrimeUQAM/steady-roll-angular pull request #4
Opened 2020-06-04 19:02 UTC by GhadaSou

2020-06-04 20:50 UTC, dbrimeUQAM requested changes

2020-06-05 02:38 UTC, MassekMeriam approved these changes

2020-06-05 03:29 UTC, GhadaSou commented on src/app/login/login.component.html
> + <div class="main-div col-md-12 text-center">
j'affiche pour le moment un simple message et je vais le changer apres par un popup,
j'ai poussé mes changements tu peux les merger

2020-06-05 14:55 UTC, sanajaziri approved these changes

2020-06-05 15:02 UTC, dbrimeUQAM commented on src/app/login/login.component.html
> + <div class="main-div col-md-12 text-center">
je fais le merge mais localement je ne vois pas le message. Pas grave si t'es au courant c'est bon.

2020-06-05 15:18 UTC, dbrimeUQAM approved these changes

2020-06-05 15:19 UTC, merged