Feature/home page component
dbrimeUQAM/steady-roll-angular pull request #7
Opened 2020-06-05 15:28 UTC by GhadaSou

2020-06-06 04:21 UTC, MassekMeriam submitted a review, later dismissed

2020-06-06 04:21 UTC, MassekMeriam commented on src/app/app.component.html
> ->>>>>>> 1e852860850fc932f3aebfb19ad2639146c6a54e
petit conflit :p

2020-06-06 04:21 UTC, MassekMeriam commented on src/app/add-article/add-article.component.html
> +<p>add-article works! ... vas-y Sana :p</p>
xD

2020-06-07 03:52 UTC, sanajaziri commented on src/app/add-article/add-article.component.html
> +<p>add-article works! ... vas-y Sana :p</p>
oki oki :)

2020-06-08 01:21 UTC, dbrimeUQAM requested changes

2020-06-08 01:21 UTC, dbrimeUQAM commented on src/app/app.component.ts
> +  } */
@GhadaSou pour qoui t'enleve ça?

2020-06-09 04:01 UTC, sanajaziri submitted a review, later dismissed

2020-06-09 14:31 UTC, dbrimeUQAM requested changes

2020-06-09 14:31 UTC, dbrimeUQAM commented on src/app/app.component.ts
> +/*     this.isLoggedIn = !!this.tokenStorageService.getToken();
@GhadaSou cette commentaire aussi il faut l'enlever.
Ca te permet facilement de savoir si l'utilisateur est connecté et son role.

2020-06-10 00:02 UTC, dbrimeUQAM approved these changes

2020-06-10 00:02 UTC, merged